### PR TITLE
Remove fees on first and last hop

### LINKED ISSUE #140: Investigate making receiver pays function public

### LINKED ISSUE #154: Remove fees for last hop if sender pays.
See https://github.com/trustlines-network/project/issues/266

### LINKED ISSUE #155: Remove fees for first hop if receiver pays.
See https://github.com/trustlines-network/project/issues/266

### PR DESCRIPTION
**Pull request by berndbohmeier**
As decided we remove the fees for the last hop, as the receiver should
not receive a fee additional to the amount he already receives.
Closes #154 

Remove the fees for the first hop if the receiver pays in alignment
to removing the fees for the last hop if the sender pays.
Closes #155

Also make transferReceiverPays function public available so that also
other users can use it.
Closes #140

### CODE REVIEW

**Comment by cducrest** [comment]
This indeed remove fees on the last hop for a regular transfer where the sender pays for the fees.
I did not look at whether _mediatedTransferReceiverPays() is still coherent after this.

**Comment by berndbohmeier** [comment]
Receiver pays is right now not coherent. This will be fixed in another pr as soon as possible.

**Comment by schmir** [comment]
> This will be fixed in another pr as soon as possible.

Can we have this in the same PR if possible?

**Comment by berndbohmeier** [comment]
I can add it in this PR if you like. I will have to add some tests, so I thought in might be easier to review separately.

**Comment by andfletcher** [comment]
How does one know who is paying for the fee? How does the sender know that the receiver will pay for the fee and vise versa?

**Comment by schmir** [comment]
Not sure if this is what @andfletcher meant. 

Currently the code emits a `Transfer` event for both the receiver pays and sender pays methods.  This is being used to show a notification in the mobile app. There's no way for an observer of the above event to know who paid the fees.

This problem is being tracked here: https://github.com/trustlines-network/contracts/issues/148

Since the receiver pays has become public, it's probably time to solve it.

**Comment by schmir** [comment]
Actually the above linked issue only mentions the BalanceUpdates. But we should have a way to decide who paid for Transfer events too.

**Pull request merged**
