### PR TITLE
Add commandline tool to deploy contracts

### LINKED ISSUE #108: Console script to easy deploy currency network with settings

### PR DESCRIPTION
**Pull request by berndbohmeier**
Use click to implement command line
Remove old deploy scripts
Closes #108

### CODE REVIEW

**Comment by berndbohmeier** [comment]
Did not mean to do that, I'll check what happened

**Comment by berndbohmeier** [comment]
I used this to clean up and upgrade the dependencies. There should be now no downgrade anymore 
@schmir

**Comment by schmir** [comment]
It might make sense to use the constraints file from the relay server, since in production it's only used as a dependency. So we run the CI tests here with the constraints from this repository, but we use it with the constraints from the relay repo. that is, it's being used with different versions.

I did this on purpose with the initial version in commit 08978995e7aaad7a009880dfe41da6

**Comment by schmir** [comment]
Even if you don't follow my reasoning here, this commit should only pin click and it's dependencies.

Upgrading and cleanup of the constraints is a different issue. It should not be part of this PR.

My recommendation would even be to remove any changes from the constraints file in this PR, get it merged, and then regenerate the constraints file of the relay server and commit the same constraints file both here and in the relay server.

**Pull request merged**
